[package]
name = "guessing_game"
version = "0.2.0"
authors = ["zen3ger", "Shane Handley <shanehandley@fastmail.com>"]
edition = "2018"

[dependencies]
piston_window = "0.89"
conrod_piston = "0.67.0"
conrod_core = "0.67.0"
find_folder="*"
rand="*"
